#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            interface.cc
            mcp_http.cc
            mcp_http_gui.cc
            mcp_http_server.cc
            handlers/analysis.cc
            handlers/automation.cc
            handlers/common.cc
            handlers/lua.cc
            handlers/markers.cc
            handlers/plugins.cc
            handlers/prompts.cc
            handlers/regions_midi.cc
            handlers/resources.cc
            handlers/session.cc
            handlers/tempo.cc
            handlers/track.cc
            handlers/tracks.cc
            handlers/transport.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_mcp_http"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './mcp_http']
    obj.name         = 'libardour_mcp_http'
    obj.target       = 'ardour_mcp_http'
    obj.uselib       = 'OSX GLIBMM GIOMM PANGOMM XML WEBSOCKETS OPENSSL'
    obj.use          = 'libardour libardour_cp libgtkmm2ext libpbd libytkmm'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')
